config:
    #Enter Your Google API Key here
    Google_API_Key: "AIzaSyAUe-ngVbEwMphBjLVLYgI3se0wn_Fg1pg"

    #Enter Your MongoDB URL here
    MongoDB_URL: "mongodb+srv://karthick7934:m638ycp3FtSq08f8@cluster0.oay1tbi.mongodb.net/?retryWrites=true&w=majority"
